### ISSUE TITLE
Misunderstanding contents from the survey paper

### ISSUE THREAD

**Issue by YuyangXueEd** [gaozhangyang/A-Survey-on-Generative-Diffusion-Model#1]
Thank you very much for your review paper, this article has benefited me a lot. These references are also invaluable. In the process of reading through the article, I encountered some questions and hope to get your answers. The paper version I read is from [arxiv](https://arxiv.org/pdf/2209.02646.pdf).

1. at Eq. $(3)$, I think the formula of the paper has one more item $F_{0t}$, and it should be $F(x,\sigma)=F_{s1}(x_s, \sigma_{s1})\circ F_{ts}(x_t,\sigma_{ts})\circ F_{0t}(x_0,\sigma_{0t})$. Is that right?
2. For the annealed Langevin dynamics algorithm, there are a duplicated for loop $\text{for } i =1 \dots L \text{ do}$, is the second one should be replaced with $\text{for } t =1 \dots T \text{ do}$? And the random noise notation is also confusing.
3. Maybe the reference [94] is not right for `CCDF` but `Cold Diffusion`, which is `Chung H, Sim B, Ye J C. Come-closer-diffuse-faster: Accelerating conditional diffusion models for inverse problems through stochastic contraction[C]//Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2022: 12413-12422.`

Looking forward to your reply. Thank you very much!

Best.

**Comment by chq1155** [comment]
Hi, 

I need to apologize for my late response first! So many thanks for you pointing out the typos. These typos are corrected in the latest version of our survey. These days, we are focusing on survey refinement, which causes a just-so-so article and my late response on GitHub. The latest version is submitted, I think it will be visible this weekend.

Thank you again!!!

Best,
Hanqun

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
