### ISSUE TITLE
Add new reference

### ISSUE THREAD

**Issue by Adamdad** [gaozhangyang/A-Survey-on-Generative-Diffusion-Model#2]
Please consider adding our paper "Diffusion Probabilistic Model Made Slim" [arxiv](https://arxiv.org/abs/2211.17106), which has just been accept by CVPR2023.

Best.

**Comment by chengtan9907** [comment]
Hi @Adamdad ,

I apologize for the delayed response and would like to express my sincere gratitude for your interest in our work. 

We have added your nice work to our GitHub. If it's convenient for you, please take a moment to review the classification to ensure it is appropriate. We will include your paper in the final version of our work.

Thank you once again for your support and please let us know if you have any further questions or concerns.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
