### ISSUE TITLE
Could you add our CVPR 2023 paper about video generation?

### ISSUE THREAD

**Issue by nihaomiao** [gaozhangyang/A-Survey-on-Generative-Diffusion-Model#3]
Hi, @chq1155, thanks a lot for your efforts to collect these works! I wonder whether you can add our CVPR 2023 paper "Conditional Image-to-Video Generation with Latent Flow Diffusion Models", which applies Diffusion models to synthesize optical flow for video generation. The links of our paper and code are [paper_link](https://arxiv.org/abs/2303.13744) and [code_link](https://github.com/nihaomiao/CVPR23_LFDM).

**Comment by chengtan9907** [comment]
Hi @nihaomiao,

I apologize for the delay in getting back to you and would like to express my sincere gratitude for your interest in our work.

We have added the information regarding your paper to our GitHub repository.  Could you please review the classification we have assigned to it to ensure that it is appropriate?  We will include your paper in the final version of our work.

Thank you again for your support and please let me know if you have any questions or concerns!

**Comment by nihaomiao** [comment]
Hi, @chengtan9907, looks pretty good! Thanks a lot for your reply and best wishes with the final version of your work!!
